### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'processed_data/casia_and_mine_triplet_xdata.npy'

### ISSUE THREAD

**Issue by Siva-Ganesh-VR** [aangfanboy/TripletLossFace#5]
Hey I'm newbie to python, I just want to learn ML so I tried to run your code in my local machine. But every time I'm keep on getting this error. 

`FileNotFoundError: [Errno 2] No such file or directory: 'processed_data/casia_and_mine_triplet_xdata.npy'`

**Comment by aangfanboy** [comment]
Please run this command before using code: `os.makedirs("processed_data")`, i will fix the code as soon as possible.

**Comment by Siva-Ganesh-VR** [comment]
While using this command I'm getting this error.
`number expected`
Any other suggestion ???

**Comment by aangfanboy** [comment]
I haven't seen an error like this, you can try `os.makedirs("processed_data", exist_ok=True)`, but what that code does is creating a folder named "processed_data" in the same path that script works. You can do the same manually.

**Comment by Siva-Ganesh-VR** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: 'processed_data/casia_and_mine_triplet_xdata.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_data_engine.py", line 359, in <module>
    real_new_x, real_new_y = md.create_main_triplet_dataset(md.real_paths, md.real_labels, 200, data_path="processed_data/casia_and_mine_triplet.npy")
  File "main_data_engine.py", line 153, in create_main_triplet_dataset
    np.save(data_path.replace(".npy", "_xdata.npy"), new_x_data)
  File "<__array_function__ internals>", line 6, in save
  File "/home/spritle/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 541, in save
    fid = open(file, "wb")
```
